### ISSUE TITLE
圆形公章弧形字的字号自适应

### ISSUE THREAD

**Issue by guanpingtang** [localhost02/SealUtil#3]
您好，感谢您的代码解决了我的问题。但我我遇到问题就是我的字体长度是变化的，我需要动态调整字号。
您的源代码如下：
`//2.字体大小，默认根据字体长度动态设定 TODO
int fontSize = font.getFontSize() == null ? (55 - fontTextLen * 2) : font.getFontSize();`
你的意思还没完成吗？写了个todo？
我个人简单的思路就是取圆的周长取3/4（2派（r-外边距）* 3/4）作为有效长度。然后根据字的总长度计算每个字的字号。暂时不知道怎么去实现。
请问您有更好思路或者提供一下实现吗？万分感谢！

**Comment by localhost02** [comment]
emm，，当时这个TODO写在这里，就是因为目前这个“字号根据字体长度自适应逻辑”还有很大缺陷，这里只是简单地根据长度来调整字号（*2是为了考虑到奇数个字的问题），需要后续进行改进。说白了，的确需要一个可靠的公式，来根据保证字体长度变化，完美地调整字号。

你的这个思路，不知道是否可行，不过可以一试呢，代码应该也能实现吧？
圆半径：circleRadius
外边距：font.getMarginSize() == null ? INIT_BEGIN : font.getMarginSize()
